const app=document.querySelector(".app"),screen=document.getElementById("screen"),pathPanel=document.getElementById("pathPanel"),resourcePanel=document.getElementById("resourcePanel");
let view="home",stageIndex=0,timer=null,remaining=0,currentStageTime=0,musicOn=false,voiceOn=true;
let musicAudio=new Audio();musicAudio.loop=true;musicAudio.volume=.55;
let voiceAudio=new Audio();voiceAudio.volume=.9;

const musicFiles={breath:"assets/audio/breath.mp3",flow:"assets/audio/flow.mp3",stillness:"assets/audio/stillness.mp3",closing:"assets/audio/closing.mp3"};

const stages=[
{title:"Awakening Breath",image:"assets/sage/breath.png",music:musicFiles.breath,voice:"assets/voice/awakening-breath.mp3",time:45,text:"Let the breath rise and fall.",sageLine:"Begin by arriving in the body. Let the breath become the first movement.",guidance:"Sit tall with both feet grounded. Inhale gently as the hands float up. Exhale as they settle back down."},
{title:"Lift & Flow",image:"assets/sage/lift-flow.png",music:musicFiles.breath,voice:"assets/voice/lift-flow.mp3",time:45,text:"Gently lift the hands.",sageLine:"Lift without effort. Imagine the hands floating on warm water.",guidance:"Raise both hands slowly as if lifting warm water. Keep the shoulders soft. Let the breath lead the motion."},
{title:"Flowing Arms",image:"assets/sage/flowing-arms.png",music:musicFiles.flow,voice:"assets/voice/flowing-arms.mp3",time:60,text:"Move as water.",sageLine:"Let one hand offer outward as the other returns. Nothing is forced.",guidance:"Guide one hand outward while the other hand returns inward. Move slowly, smoothly, and without strain."},
{title:"Gather Qi",image:"assets/sage/gather-qi.png",music:musicFiles.flow,voice:"assets/voice/gather-qi.mp3",time:45,text:"Bring energy inward.",sageLine:"Gather the movement back to your center. Calm collects where attention rests.",guidance:"Draw the hands toward the lower belly. Imagine gathering calm into your center. Let the elbows relax downward."},
{title:"Stillness",image:"assets/sage/stillness.png",music:musicFiles.stillness,voice:"assets/voice/stillness.mp3",time:30,text:"Pause and soften.",sageLine:"Stillness is not empty. It is where the body listens.",guidance:"Rest the hands. Let the shoulders drop. Notice the breath without forcing it."},
{title:"Closing",image:"assets/sage/closing.png",music:musicFiles.closing,voice:"assets/voice/closing.mp3",time:35,text:"Complete the practice.",sageLine:"Let the practice settle. Carry the quiet with you.",guidance:"Bring the hands together. Let the breath slow. Feel the practice settle into the body."},
{title:"Final Bow",image:"assets/sage/bow.png",music:musicFiles.closing,voice:"assets/voice/final-bow.mp3",time:25,text:"Strength and stillness in balance.",sageLine:"Palm covers fist. Strength rests within peace.",guidance:"Open palm covers the fist. Bow the head gently while keeping the eyes forward. End with gratitude."}
];

function brandLogo(){return `<div class="brand" aria-label="Stillwater"><div class="brand-mark" aria-hidden="true"></div><div><div class="brand-title">Stillwater</div><div class="brand-subtitle">Find your center</div></div></div>`}
function musicButton(){return `<button class="secondary music-toggle" onclick="toggleMusic()">${musicOn?"Music Off":"Music On"}</button>`}
function voiceButton(){return `<button class="secondary voice-toggle" onclick="toggleVoice()">${voiceOn?"Voice Off":"Voice On"}</button>`}
function audioStatus(){return `<p class="audio-status ${(musicOn||voiceOn)?"audio-on":""}">${musicOn?"Music on":"Music off"} · ${voiceOn?"Voice on":"Voice off"}</p>`}
function setHomeLayout(){app.classList.add("home-mode");pathPanel.classList.add("hidden");resourcePanel.classList.add("hidden");pathPanel.innerHTML="";resourcePanel.innerHTML=""}
function setSessionLayout(){app.classList.remove("home-mode");pathPanel.classList.remove("hidden");resourcePanel.classList.remove("hidden");pathPanel.innerHTML=buildPathTree();resourcePanel.innerHTML=buildResourcePanel()}

function home(){clearInterval(timer);view="home";setHomeLayout();screen.innerHTML=`${brandLogo()}<img src="assets/sage/idle.png" class="sage-img" alt="Sage the Stillwater Sensei"><p class="prompt">Come as you are.</p><div class="controls"><button onclick="showPlan()">Begin</button>${musicButton()}${voiceButton()}</div><p class="small">Guided by Sage the Stillwater Sensei</p>${audioStatus()}`}
function showPlan(){clearInterval(timer);view="plan";setHomeLayout();const list=stages.map(s=>`<li><strong>${s.title}</strong> · ${s.time}s</li>`).join("");screen.innerHTML=`${brandLogo()}<h2>Today’s Path</h2><img src="assets/sage/idle.png" class="sage-img" alt="Sage preparing the session"><p class="prompt">A short seated practice is ready.</p><ol class="stage-list">${list}</ol><div class="controls"><button onclick="start()">Begin Session</button>${musicButton()}${voiceButton()}<button class="secondary" onclick="home()">Return</button></div>${audioStatus()}`}
function start(){stageIndex=0;view="session";runStage(true,true)}

function runStage(resetTimer=true,playVoiceNow=false){clearInterval(timer);if(stageIndex>=stages.length){complete();return}view="session";setSessionLayout();const s=stages[stageIndex];if(resetTimer){remaining=s.time;currentStageTime=s.time}if(musicOn)playStageMusic(s.music);if(voiceOn&&playVoiceNow)playVoice(s.voice);const percent=((currentStageTime-remaining)/currentStageTime)*100;screen.innerHTML=`<div class="stage-count">Stage ${stageIndex+1} of ${stages.length}</div><h2>${s.title}</h2><img src="${s.image}" class="sage-img" alt="${s.title}"><p class="prompt">${s.text}</p><p class="sage-line">“${s.sageLine}”</p><p class="guidance">${s.guidance}</p><div class="timer" id="t">${format(remaining)}</div><div class="progress-track"><div class="progress-fill" id="progress" style="width:${percent}%"></div></div><div class="controls"><button onclick="pause()">Pause</button><button class="secondary" onclick="back()">Back</button><button class="secondary" onclick="next()">Forward</button>${musicButton()}${voiceButton()}<button class="secondary" onclick="home()">End</button></div>${audioStatus()}`;timer=setInterval(updateStageTimer,1000)}
function updateStageTimer(){remaining--;const td=document.getElementById("t"),pr=document.getElementById("progress");if(td)td.textContent=format(remaining);if(pr)pr.style.width=((currentStageTime-remaining)/currentStageTime)*100+"%";if(remaining<=0){clearInterval(timer);setTimeout(next,1000)}}
function pause(){clearInterval(timer);view="paused";setSessionLayout();const s=stages[stageIndex];screen.innerHTML=`<h2>Paused</h2><img src="${s.image}" class="sage-img" alt="${s.title}"><p class="prompt">Stillness is part of the practice.</p><div class="timer">${format(remaining)}</div><div class="controls"><button onclick="resume()">Resume</button><button class="secondary" onclick="back()">Back</button><button class="secondary" onclick="next()">Forward</button>${musicButton()}${voiceButton()}<button class="secondary" onclick="home()">End Session</button></div>${audioStatus()}`}
function resume(){runStage(false,false)}
function next(){stageIndex++;runStage(true,true)}
function back(){if(stageIndex>0)stageIndex--;runStage(true,true)}
function complete(){clearInterval(timer);view="complete";setHomeLayout();if(musicOn)playStageMusic(musicFiles.closing);screen.innerHTML=`${brandLogo()}<h2>Session Complete</h2><img src="assets/sage/bow.png" class="sage-img" alt="Sage final bow"><p class="prompt">You arrived.<br>You moved.<br>You return.</p><div class="controls"><button onclick="home()">Return Home</button>${musicButton()}${voiceButton()}</div>${audioStatus()}`}

function buildPathTree(){return `<div class="path-title">Stillwater Path</div>`+stages.map((s,i)=>{let state=i<stageIndex?"done":i===stageIndex?"active":"";return `<div class="path-item ${state}"><span class="path-dot"></span><span>${s.title}</span></div>`}).join("")}
function buildResourcePanel(){return `<div class="resource-title">Resources</div><div class="resource-list"><a class="resource-link" href="#">Find a local Tai Chi / Qigong instructor</a><a class="resource-link" href="#">Learn about VA Tai Chi for Vets</a><a class="resource-link" href="#">Overview of Tai Chi and Qigong</a><a class="resource-link" href="#">About the developer</a></div><p class="resource-note">Links will be activated in a future update.</p>`}

function toggleMusic(){musicOn=!musicOn;if(musicOn){if(view==="session"||view==="paused")playStageMusic(stages[stageIndex].music);else if(view==="complete")playStageMusic(musicFiles.closing);else playStageMusic(musicFiles.breath)}else stopMusic();renderCurrentViewAfterAudioToggle()}
function toggleVoice(){voiceOn=!voiceOn;if(!voiceOn)stopVoice();else if(view==="session"||view==="paused")playVoice(stages[stageIndex].voice);renderCurrentViewAfterAudioToggle()}
function playStageMusic(src){if(!src)return;const current=musicAudio.getAttribute("data-src");if(current!==src){musicAudio.pause();musicAudio=new Audio(src);musicAudio.loop=true;musicAudio.volume=.55;musicAudio.setAttribute("data-src",src);musicAudio.addEventListener("ended",()=>{musicAudio.currentTime=0;musicAudio.play().catch(()=>{})})}musicAudio.play().catch(()=>{})}
function stopMusic(){musicAudio.pause();musicAudio.currentTime=0}
function playVoice(src){if(!src)return;stopVoice();voiceAudio=new Audio(src);voiceAudio.volume=.9;voiceAudio.play().catch(()=>{})}
function stopVoice(){voiceAudio.pause();voiceAudio.currentTime=0}
function renderCurrentViewAfterAudioToggle(){if(view==="home")home();else if(view==="plan")showPlan();else if(view==="session")runStage(false,false);else if(view==="paused")pause();else if(view==="complete")complete();else home()}
function format(s){const safe=Math.max(0,s),m=Math.floor(safe/60),sec=safe%60;return m+":"+sec.toString().padStart(2,"0")}
home();
